/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oprosshmakov;

/**
 *
 * @author Шмаков
 */
public class OprosSH extends javax.swing.JFrame {

    /**
     * Creates new form OprosSH
     */
    public OprosSH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        AnimateSneg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel1.setText("Опрос от Шмакова");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 560));
        setMinimumSize(new java.awt.Dimension(420, 560));
        setPreferredSize(new java.awt.Dimension(420, 560));
        setSize(new java.awt.Dimension(420, 560));
        getContentPane().setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oprosshmakov/logo2.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 10, 160, 50);

        jButton1.setText("Выход");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 530, 72, 23);

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel2.setText("Опрос от Шмакова");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 60, 183, 23);

        jLabel3.setText("Как вы себя чуствуете?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 90, 130, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Отлично");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(140, 110, 72, 21);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Хорошо");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(140, 130, 69, 21);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Нормально");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(140, 150, 88, 21);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Не очень");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(140, 170, 74, 21);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Плохо");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(140, 190, 59, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Нужна ли вам консультация с психологом?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 220, 273, 20);

        jRadioButton6.setText("Да");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(130, 250, 37, 21);

        jRadioButton7.setText("Нет");
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(200, 250, 43, 21);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Коментарий");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 280, 78, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 310, 234, 86);

        jButton2.setText("Отправить");
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 460, 88, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 430, 100, 22);

        AnimateSneg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oprosshmakov/SnowCrystalPNG_1.png"))); // NOI18N
        AnimateSneg.setName(""); // NOI18N
        AnimateSneg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClickMouse(evt);
            }
        });
        getContentPane().add(AnimateSneg);
        AnimateSneg.setBounds(310, 10, 100, 100);

        jLabel6.setText("Введите свой email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 410, 130, 16);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Пользователь\\Desktop\\ПП ПМ.02 Шмаков\\Приложение ПМ.02\\OprosShmakov\\src\\oprosshmakov\\backgroundNE_1.jpg")); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setName(""); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 420, 570);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClickMouse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickMouse
        // TODO add your handling code here:

        final int MAX_Y = 450;
        final int MIN_Y = 50;

        Thread animation = new Thread(new Runnable() {
            @Override
            public void run() {
                int x = 310;
                int y = 30;
                boolean checked = true;
                while (true) {
                    if (checked) {
                        AnimateSneg.setLocation(x, y);
                        y += 10;
                    } else {
                        AnimateSneg.setLocation(x, y);
                        y -= 10;
                    }
                    if (y > MAX_Y) {
                        checked = false;
                        y = 400;
                    }
                    if (y < MIN_Y) {
                        checked = true;
                    }
                    try {
                        Thread.sleep(200);
                    } catch (Exception e) {

                    }
                }
            }

        });
        animation.start();

    }//GEN-LAST:event_ClickMouse

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OprosSH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OprosSH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OprosSH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OprosSH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OprosSH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnimateSneg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
